# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/servo_tests_const.xdc

# IP: C:/Users/dschussheim/Documents/GitHub/digital-servo/firmware/ipcore_dir/dds_LUT_pw24_ow16.xco
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dds_LUT_pw24_ow16 || ORIG_REF_NAME==dds_LUT_pw24_ow16}]

# IP: C:/Users/dschussheim/Documents/GitHub/digital-servo/firmware/ipcore_dir/dds_LUT_pw24_ow24.xco
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dds_LUT_pw24_ow24 || ORIG_REF_NAME==dds_LUT_pw24_ow24}]

# IP: C:/Users/dschussheim/Documents/GitHub/digital-servo/firmware/ipcore_dir/dds_PG_pw24.xco
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dds_PG_pw24 || ORIG_REF_NAME==dds_PG_pw24}]
