# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/dschussheim/Documents/GitHub/digital-servo/M_KX1_DB/Firmware/servo_tests/servo_tests_new/servo_tests_new.srcs/sources_1/ip/multiplier35x35k7/multiplier35x35k7.xci
# IP: The module: 'multiplier35x35k7' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/dschussheim/Documents/GitHub/digital-servo/M_KX1_DB/Firmware/servo_tests/servo_tests_new/servo_tests_new.srcs/sources_1/ip/multiplier35x35k7/multiplier35x35k7_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'multiplier35x35k7'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/dschussheim/Documents/GitHub/digital-servo/M_KX1_DB/Firmware/servo_tests/servo_tests_new/servo_tests_new.srcs/sources_1/ip/multiplier35x35k7/multiplier35x35k7.xci
# IP: The module: 'multiplier35x35k7' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/dschussheim/Documents/GitHub/digital-servo/M_KX1_DB/Firmware/servo_tests/servo_tests_new/servo_tests_new.srcs/sources_1/ip/multiplier35x35k7/multiplier35x35k7_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'multiplier35x35k7'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
