######################################################################
##
## Filename: counter4.udo
## Created on: Fri May 12 5:01:58 PM Eastern Daylight Time 2017
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
