# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7k160tffg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/dschussheim/Documents/GitHub/digital-servo/PSU/Firmware/KX2/Second_Order_Filter_Test/second_order_filter_test.cache/wt [current_project]
set_property parent.project_path C:/Users/dschussheim/Documents/GitHub/digital-servo/PSU/Firmware/KX2/Second_Order_Filter_Test/second_order_filter_test.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/dschussheim/Documents/GitHub/digital-servo/PSU/Firmware/KX2/Second_Order_Filter_Test/second_order_filter_test.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/dschussheim/Documents/GitHub/digital-servo/PSU/Firmware/KX2/Second_Order_Filter_Test/AD9783.v
  C:/Users/dschussheim/Documents/GitHub/digital-servo/PSU/Firmware/KX2/Second_Order_Filter_Test/second_order_filter_test.srcs/sources_1/new/IIR2ndOrderFast.v
  C:/Users/dschussheim/Documents/GitHub/digital-servo/PSU/Firmware/KX2/Second_Order_Filter_Test/LTC2195x2delay.v
  C:/Users/dschussheim/Documents/GitHub/digital-servo/PSU/Firmware/KX2/Second_Order_Filter_Test/timescale.v
  C:/Users/dschussheim/Documents/GitHub/digital-servo/PSU/Firmware/KX2/Second_Order_Filter_Test/SPI.v
  C:/Users/dschussheim/Documents/GitHub/digital-servo/PSU/Firmware/KX2/Second_Order_Filter_Test/clk_div.v
  C:/Users/dschussheim/Documents/GitHub/digital-servo/PSU/Firmware/KX2/Second_Order_Filter_Test/reset.v
  C:/Users/dschussheim/Documents/GitHub/digital-servo/PSU/Firmware/KX2/Second_Order_Filter_Test/second_order_filter_test.srcs/sources_1/new/SecondOrderTest.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/dschussheim/Documents/GitHub/digital-servo/PSU/Firmware/KX2/Second_Order_Filter_Test/KX2const.xdc
set_property used_in_implementation false [get_files C:/Users/dschussheim/Documents/GitHub/digital-servo/PSU/Firmware/KX2/Second_Order_Filter_Test/KX2const.xdc]


synth_design -top SecondOrderTest -part xc7k160tffg676-2


write_checkpoint -force -noxdef SecondOrderTest.dcp

catch { report_utilization -file SecondOrderTest_utilization_synth.rpt -pb SecondOrderTest_utilization_synth.pb }
