######################################################################
##
## Filename: clock_test.udo
## Created on: Fri May 12 4:05:24 PM Eastern Daylight Time 2017
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
