set_property SRC_FILE_INFO {cfile:C:/Users/dschussheim/Documents/GitHub/digital-servo/M_KX1_DB/Firmware/servo_tests/Servo_partial_reconfig/servo_partial_reconfig/servo_tests_const.xdc rfile:../servo_tests_const.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter clk 0.000
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name ADC2/LTC2195_SPI_inst/spi_clk -source [get_ports clk] -divide_by 1 [get_pins ADC2/LTC2195_SPI_inst/spi_clk_reg/Q]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name ADC2/PS_clk -source [get_ports clk] -divide_by 1 [get_pins ADC2/PS_clk_reg/Q]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {ADC2/spi_data[7]} -source [get_ports clk] -divide_by 1 [get_pins {ADC2/spi_data_reg[7]/Q}]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {ADC2/spi_data[8]} -source [get_ports clk] -divide_by 1 [get_pins {ADC2/spi_data_reg[8]/Q}]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {ADC2/spi_data[9]} -source [get_ports clk] -divide_by 1 [get_pins {ADC2/spi_data_reg[9]/Q}]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name ADC2/spi_trigger_reg_n_0 -source [get_ports clk] -divide_by 1 [get_pins ADC2/spi_trigger_reg/Q]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name rstLEDclk/clk__0 -source [get_ports clk] -divide_by 1 [get_pins rstLEDclk/div_clk_reg/Q]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name rst_in -source [get_pins rstLEDclk/div_clk_reg/Q] -divide_by 1 [get_pins rst_in_reg/Q]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name ENC_p -source [get_pins ADC2/ODDR_inst/C] -divide_by 1 -invert [get_ports ENC_p]
