set_property PACKAGE_PIN U9       [get_ports leds[3]]
set_property IOSTANDARD  LVCMOS15   [get_ports leds[3]]
set_property PACKAGE_PIN V12      [get_ports leds[2]]
set_property IOSTANDARD  LVCMOS15   [get_ports leds[2]]
set_property PACKAGE_PIN V13      [get_ports leds[1]]
set_property IOSTANDARD  LVCMOS15   [get_ports leds[1]]
set_property PACKAGE_PIN W13      [get_ports leds[0]]
set_property IOSTANDARD  LVCMOS15   [get_ports leds[0]]

set_property PACKAGE_PIN AE23       [get_ports bnc[3]]
set_property IOSTANDARD  LVCMOS25   [get_ports bnc[3]]
set_property PACKAGE_PIN AF24       [get_ports bnc[2]]
set_property IOSTANDARD  LVCMOS25   [get_ports bnc[2]]
set_property PACKAGE_PIN Y22        [get_ports bnc[1]]
set_property IOSTANDARD  LVCMOS25   [get_ports bnc[1]]
set_property PACKAGE_PIN AD25       [get_ports bnc[0]]
set_property IOSTANDARD  LVCMOS25   [get_ports bnc[0]]

set_property PACKAGE_PIN AF23       [get_ports gnd[3]]
set_property IOSTANDARD  LVCMOS25   [get_ports gnd[3]]
set_property PACKAGE_PIN AF25       [get_ports gnd[2]]
set_property IOSTANDARD  LVCMOS25   [get_ports gnd[2]]
set_property PACKAGE_PIN AA22       [get_ports gnd[1]]
set_property IOSTANDARD  LVCMOS25   [get_ports gnd[1]]
set_property PACKAGE_PIN AE25       [get_ports gnd[0]]
set_property IOSTANDARD  LVCMOS25   [get_ports gnd[0]]