# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7k160tffg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/dschussheim/Documents/GitHub/digital-servo/PSU/Firmware/KX2/ADC_DAC_KX2/ADC_DAC_KX2.cache/wt [current_project]
set_property parent.project_path C:/Users/dschussheim/Documents/GitHub/digital-servo/PSU/Firmware/KX2/ADC_DAC_KX2/ADC_DAC_KX2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/dschussheim/Documents/GitHub/digital-servo/PSU/Firmware/KX2/ADC_DAC_KX2/ADC_DAC_KX2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/dschussheim/Documents/GitHub/digital-servo/PSU/Firmware/KX2/ADC_DAC_KX2/AD9783.v
  C:/Users/dschussheim/Documents/GitHub/digital-servo/PSU/Firmware/KX2/ADC_DAC_KX2/ADC_DAC_KX2.srcs/sources_1/new/LTC2195x2delay.v
  C:/Users/dschussheim/Documents/GitHub/digital-servo/PSU/Firmware/KX2/ADC_DAC_KX2/timescale.v
  C:/Users/dschussheim/Documents/GitHub/digital-servo/PSU/Firmware/KX2/ADC_DAC_KX2/SPI.v
  C:/Users/dschussheim/Documents/GitHub/digital-servo/PSU/Firmware/KX2/ADC_DAC_KX2/clk_div.v
  C:/Users/dschussheim/Documents/GitHub/digital-servo/PSU/Firmware/KX2/ADC_DAC_KX2/reset.v
  C:/Users/dschussheim/Documents/GitHub/digital-servo/PSU/Firmware/KX2/ADC_DAC_KX2/ADC_DAC_KX2.srcs/sources_1/new/ADC_DAC_test_KX2.v
  C:/Users/dschussheim/Documents/GitHub/digital-servo/PSU/Firmware/KX2/ADC_DAC_KX2/LTC2195x2.v
  C:/Users/dschussheim/Documents/GitHub/digital-servo/PSU/Firmware/KX2/ADC_DAC_KX2/Sweep.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/dschussheim/Documents/GitHub/digital-servo/PSU/Firmware/KX2/ADC_DAC_KX2/ADC_DAC_KX2.srcs/constrs_1/new/ADC_DAC_KX2_const.xdc
set_property used_in_implementation false [get_files C:/Users/dschussheim/Documents/GitHub/digital-servo/PSU/Firmware/KX2/ADC_DAC_KX2/ADC_DAC_KX2.srcs/constrs_1/new/ADC_DAC_KX2_const.xdc]


synth_design -top ADC_DAC_test_KX2 -part xc7k160tffg676-2


write_checkpoint -force -noxdef ADC_DAC_test_KX2.dcp

catch { report_utilization -file ADC_DAC_test_KX2_utilization_synth.rpt -pb ADC_DAC_test_KX2_utilization_synth.pb }
